### ISSUE TITLE
problem with submodule update

### ISSUE THREAD

**Issue by danice** [materializecss/materialize-docs#10]
Commit "ci: update submodule" (e42a8228b5467eea14833a8d4e8b390a5e5e6e90) cannot be checked because includes a materialize submodule commit "05bf70fb897bea1c6db546ad4395a2691da2c261" that is not available in github. 

Can you push this 05bf70fb897bea1c6db546ad4395a2691da2c261 or overwritte last materialize-docs commit to a valid submodule position.. thanks!

**Comment by wuda-io** [comment]
Hi, sorry I am still learning with the monorepo setup. As I get used to it, it is very nice to work with.
So, I guess, I have to push the changes of the submodule(s) first and then push the docs?
It should work now.
